FROM docker.elastic.co/elasticsearch/elasticsearch:7.9.1

# install metricbeat
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.9.1-x86_64.rpm
RUN rpm -vi metricbeat-7.9.1-x86_64.rpm
